baseURL = "https://kan-bayashi.github.io/DiscreTalk"
languageCode = "en-us"
title = "DiscreTalk: Text-to-Speech as a Machine Translation Problem"
theme = "paper"

[markup.goldmark.renderer]
unsafe= true
